### ISSUE TITLE
你好！我有个问题想请教一下？

### ISSUE THREAD

**Issue by BCWang93** [Walleclipse/iWildCam_2019_FGVC6#1]
我在阅读您的代码的时候，发现您在训练过程中保存模型的时候是采用的固定步长来保存的模型。我想问的是，如果以f1score或者是acc为基准，当当前模型在验证集上的f1score大于当前最好的f1score的时候就进行保存。这样的话会不会更好一点儿啊？避免随机性的问题？谢谢！另外一点就是，我想问下，如果按照您的这种方法，最后的话，您是怎么来选择效果最好的模型在测试集上进行测试的呢？谢谢！

**Comment by Walleclipse** [comment]
你好,
1. 按照你说的在验证集上为基准保存模型然后用于测试集也是可以的。但是 iWildCam_2019_FGVC6 这个问题当中测试集与验证集分布非常不一样。所以验证集上好的模型很有可能在测试集上不太好 (有可能过拟合到验证集上了)，所以我就训练固定步数，采取了特定步数的模型来计算测试集。 但是一般的问题当中，如果验证集和测试集分布差别不大，那么按照你说的验证集上的性能保存的方法确实很好。
2. 我就训练了固定的步数，比如20个epoch，然后把这个当做最后的模型。我反而觉得根据验证集性能保存有更高的随机性。
