### ISSUE TITLE
something about data prepare

### ISSUE THREAD

**Issue by XDUSPONGE** [Walleclipse/iWildCam_2019_FGVC6#2]
您好 
我是最近接触到这个野生动物识别的数据，关于数据方面有些问题向您请教一下
* 首先，您是使用了一个检测算法，将原始图像中的animal crop出来，想问一下，您主要是使用的什么算法去crop的呢，这边的Camera Trap Animals Detection Result是您跑出来的结果吗
* 在使用detect_crop_image时候，detect_train_images是没有问题的，而在detect_test_images则出现了问题，我看了一下主要是会调用pd.read_csv(DATA_DIR + 'raw_data/test_file_orig.csv')，而在preprep data的时候是没有这个raw data的，想问一下这个文件是哪里来的
谢谢

**Comment by Walleclipse** [comment]
你好，
我用的是赛事主办方提供的detection结果，这个detection结果你可以在[detection_result](https://lilablobssc.blob.core.windows.net/iwildcam2019/Detection_Results.tar.gz) 下载。  
更多有关数据的说明请查看 [data](https://github.com/Walleclipse/iWildCam_2019_FGVC6/blob/master/data/README.md)。
官方说明在[iwildcam_comp](https://github.com/visipedia/iwildcam_comp/tree/master/2019), 官方的detection结果是 Faster-RCNN model with Inception-Resnet-v2 backbone and atrous convolution 算法下跑出来的。
